# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:4.1.2

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install && npm run build
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm install && npm run build
            - git config git-ftp.syncroot dist/
            - git ftp push --user $Username --passwd $Pwd ftp://ftp.Smarterasp.net

